# Generated by Django 5.2.14 on 2026-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_venda_itemvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_nota_fiscal',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
